services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: jesttest
      POSTGRES_PASSWORD: jesttest
      POSTGRES_DB: gosagora-test-db
    ports:
      - 5433:5432
    volumes:
      - ../data/test/postgres/data:/var/lib/postgresql/data
