services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: gosagora-dev-db
    ports:
      - 5432:5432
    volumes:
      - ../data/dev/postgres/data:/var/lib/postgresql/data
